version: '3.8'

services:
  frontend:
    image: frontend-image:latest
    ports:
      - "8000:8000"
    restart: always

  backend:
    image: backend-image:latest
    ports:
      - "8080:8080"
    restart: always
